<?php
/**
 * @var App\Blocks\BooksBlock $this
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>


    <?php require_once 'App/templates/stylesTemplate.php'?>
</head>
<body>
<div style="display: flex; flex-direction: column; align-items: flex-start">
<?php include 'App/templates/headerTemplate.phtml'?>

<div class="content-container content-container_list">

    <div class="entity-container entity-container_list">
        <?php foreach ($this->getData() as $book): ?>
        <div class="entity-container__info-block entity-container__info-block_list">
            <h2><?= $book['name']?></h2>
            <h3><?= $book['author']?></h3>
        </div>
        <?php endforeach; ?>
    </div>

    <div class="recommend-list">
        <a
            href=""
            class="recommend-list__element"
        >
            Худ. литература
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Научная литература
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Отечественная
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Зарубежная
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Достоевский
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Пушкин
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Философия
        </a>

        <a
                href=""
                class="recommend-list__element"
        >
            Другое
        </a>
    </div>
</div>

<?php include 'App/templates/footerTemplate.phtml'?>
</div>
</body>
</html>