<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for author
 */

$model = $this->getAuthor();
?>

<div class="content-container">
    <div class="entity-container">
        <div class="entity-container__side-block">
            <div class="entity-container__info-block">
                <h2><?= $this->toNormalText($model->getName()) ?></h2>
            </div>

            <div class="entity-container__left-buttons">
                <a href="/editAuthor?id=<?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                    Редактировать
                </a>

                <a href="/deleteAuthor?id= <?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                    Удалить
                </a>
            </div>
        </div>

        <div class="entity-container__side-block">
            <div class="entity-container__info-block entity-container__info-block_table">
                <div class="table">
                    <div class="table__header">
                        <div class="table__field">Дата</div>
                        <div class="table__field">Книга</div>
                    </div>
                    <?php foreach ($model->getBooks() as $book): ?>
                        <div class="table__row">
                            <div class="table__field"><?= $this->toNormalText($book->getYear()) ?></div>
                            <div class="table__field"><?= $this->toNormalText($book->getName()) ?></div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>
            <a href="/books?author_id=<?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                Все книги
            </a>
        </div>
    </div>
</div>
