<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for author
 */
?>

<div class="content-container">
    <div class="entity-container">
        <div class="entity-container__side-block">

            <?php
            $data = $this->model->getData();
            ?>
            <div class="entity-container__info-block">
                <h2><?= $data['name'] ?></h2>
            </div>

            <div class="entity-container__left-buttons">
                <a href="/editAuthor?id=<?= $data['id']?>" class="entity-container__button">
                    Редактировать
                </a>

                <a href="" class="entity-container__button">
                    биография
                </a>
            </div>
        </div>

        <div class="entity-container__side-block">
            <div class="entity-container__info-block entity-container__info-block_table">
                <div class="table">
                    <div class="table__header">
                        <div class="table__field">кол-во</div>
                        <div class="table__field">Книга</div>
                    </div>
                    <?php foreach ($this->model->getBooks() as $author): ?>
                        <div class="table__row">
                            <div class="table__field"><?=$author['year'] ?></div>
                            <div class="table__field"><?=$author['name'] ?></div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>
            <a href="/books?author_id=<?= $data['id']?>" class="entity-container__button">
                Все книги
            </a>
        </div>
    </div>
</div>
