<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for books
 */

$model = $this->getBooks()
?>

<div class="content-container content-container_list">

    <div class="entity-container entity-container_list">
        <?php foreach ($model->getList() as $book): ?>
            <a href="/book?id=<?= $this->toNormalText($book->getId()) ?>" class="entity-container__button">
                <h2><?= $this->toNormalText($book->getName()) ?></h2>
                <h3><?= $this->toNormalText($book->getAuthor()) ?></h3>
            </a>
        <?php endforeach; ?>
    </div>

    <div class="recommend-list">
        <a href="" class="recommend-list__element">
            Худ. литература
        </a>

        <a href="" class="recommend-list__element">
            Научная литература
        </a>

        <a href="" class="recommend-list__element">
            Отечественная
        </a>

        <a href="" class="recommend-list__element">
            Зарубежная
        </a>

        <a href="" class="recommend-list__element">
            Достоевский
        </a>

        <a href="" class="recommend-list__element">
            Пушкин
        </a>

        <a href="" class="recommend-list__element">
            Философия
        </a>

        <a href="/createBook" class="recommend-list__element">
            Добавить книгу
        </a>
    </div>
</div>
