<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for book
 */

$model = $this->getModel();
?>

<div class="content-container">
    <div class="entity-container">
        <div class="entity-container__side-block">
            <div class="entity-container__info-block">
                <h2><?= $this->toNormalText($model->getName()) ?></h2>
                <p><?= $this->toNormalText($model->getAuthor()) ?></p>
            </div>

            <div class="entity-container__info-block">
                <p>
                    category
                </p>
                <p>
                    <?= $this->toNormalText($model->getCountry()) . ' ' . $this->toNormalText($model->getYear()) ?>
                </p>
                <p>
                    <?= 'Издатель: ' . $this->toNormalText($model->getPublisher()) ?>
                </p>
                <p>
                    <?= 'Цена: ' . $this->toNormalText($model->getPrice()) . 'p'?>
                </p>
            </div>

            <div class="entity-container__left-buttons">
                <a href="/editBook?id=<?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                    Редактировать
                </a>

                <a href="/deleteBook?id=<?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                    Удалить
                </a>

                <a href="/author?id=<?= $this->toNormalText($model->getAuthorId()) ?>" class="entity-container__button">
                    Автор
                </a>
            </div>
            <a href="/takeBook?id=<?= $this->toNormalText($model->getId()) ?>" class="entity-container__button">
                Взять книгу
            </a>
        </div>

        <div class="entity-container__side-block">
            <div class="entity-container__info-block entity-container__info-block_table">
                <div class="table">
                    <div class="table__header">
                        <div class="table__field">кол-во</div>
                        <div class="table__field">библиотека</div>
                    </div>
                    <?php foreach ($model->getLibs() as $book): ?>
                        <div class="table__row">
                            <div class="table__field"><?= $this->toNormalText($book->getCount()) ?></div>
                            <div class="table__field"><?= $this->toNormalText($book->getName()) ?></div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>

            <a href="" class="entity-container__button">
                Весь список
            </a>
        </div>
    </div>
</div>
