<?php
/**
 * @var App\Blocks\Block $this $this of block class for book
 */
?>

<div class="content-container">
    <div class="entity-container">
        <div class="entity-container__side-block">

            <?php
                $data = $this->model->getData();
            ?>
            <div class="entity-container__info-block">
                <h2><?= $data['book_name'] ?></h2>
                <p><?= $data['author'] ?></p>
            </div>

            <div class="entity-container__info-block">
                <p>
                    category
                </p>
                <p>
                    <?= $data['country'] . ' ' . $data['book_date'] ?>
                </p>
                <p>
                    <?= 'Издатель: ' . $data['publisher']?>
                </p>
                <p>
                    <?= 'Цена: ' . $data['book_price'] . 'p'?>
                </p>
            </div>

            <div class="entity-container__left-buttons">
                <a href="" class="entity-container__button">
                    Жанр
                </a>

                <a href="/author?id=<?= $data['author_id'] ?>" class="entity-container__button">
                    Автор
                </a>
            </div>
        </div>

        <div class="entity-container__side-block">
            <div class="entity-container__info-block entity-container__info-block_table">
                <div class="table">
                    <div class="table__header">
                        <div class="table__field">кол-во</div>
                        <div class="table__field">библиотека</div>
                    </div>
                    <?php foreach ($this->model->getLibs() as $library): ?>
                        <div class="table__row">
                            <div class="table__field"><?=$library['count'] ?></div>
                            <div class="table__field"><?=$library['library'] ?></div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>

            <a href="" class="entity-container__button">
                Весь список
            </a>
        </div>
    </div>
</div>
