<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for creation
 */
?>
<div class="content-container">
    <div class="entity-container">
            <form method="post" action="">
                <div class="entity-container__input-row">

                    <input
                        id="token"
                        name="token"
                        type="hidden"
                        value="<?= $this->getToken() ?>"
                    >

                    <label for="authorName">
                        ФИО автора:
                    </label>
                    <input
                        id="authorName"
                        name="authorName"
                        placeholder="ФИО автора"
                        value="<?= $this->model->getData()['name'] ?>"
                        required
                    >

                    <input
                        class="entity-container__button entity-container__button_small"
                        type="submit"
                        name="newLib"
                    >
                </div>
            </form>
        </div>
</div>