<?php
/**
 * @var App\Core\Blocks\Block $this->model $this of block class for creation
 */
$model = $this->getAuthor();
?>
<div class="content-container">
    <div class="entity-container">
            <form method="post" action="">
                <div class="entity-container__input-row">
                    <?php $this->renderToken() ?>

                    <label for="authorName">
                        ФИО автора:
                    </label>
                    <input
                        id="authorName"
                        name="authorName"
                        placeholder="ФИО автора"
                        value="<?= $model->getName() ?>"
                        required
                    >

                    <input
                        class="entity-container__button entity-container__button_small"
                        type="submit"
                        name="newLib"
                    >
                </div>
            </form>
        </div>
</div>