<?php
/**
 * @var App\Core\Blocks\Block $this->model $this of block class for creation
 */
$model = $this->getLibrary();
?>
<div class="content-container">

    <form method="post" action="">
        <div class="entity-container entity-container_column">
            <?php $this->renderToken() ?>

            <div class="entity-container__input-row">
                <label for="libName"> Название библиотеки</label>
                <input
                    id="libName"
                    name="libName"
                    placeholder="Название библиотеки"
                    value="<?= $model->getName() ?>"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <label for="address"> Адрес</label>
                <input
                    id="address"
                    name="libAddress"
                    placeholder="Адрес"
                    value="<?= $model->getAddress() ?>"
                    required
                >
            </div>

            <input
                class="entity-container__button entity-container__button_small"
                type="submit"
                  name="newLib"
            >
        </div>
    </form>
</div>
