<?php
/**
 * @var App\Blocks\BlockAbstract $this $this of block class for creation
 * @var App\Blocks\BlockAbstract $authors $this of block class for authors
 * @var App\Blocks\BlockAbstract $countries $this of block class for countries
 * @var App\Blocks\BlockAbstract $publishers $this of block class for publishers
 */
?>
<div class="content-container">

    <form method="post" action="">
        <div class="entity-container entity-container_column">

            <div class="entity-container__input-row">
                <label for="libName"> Название библиотеки</label>
                <input
                    id="libName"
                    name="libName"
                    placeholder="Название библиотеки"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <label for="address"> Адрес</label>
                <input
                    id="address"
                    name="libAddress"
                    placeholder="Адрес"
                    required
                >
            </div>

            <input
                class="entity-container__button entity-container__button_small"
                type="submit"
                  name="newLib"
            >
        </div>
    </form>
</div>
