<?php
/**
 * @var App\Blocks\BlockAbstract $this $this of block class for creation
 * @var App\Blocks\BlockAbstract $authors $this of block class for authors
 * @var App\Blocks\BlockAbstract $countries $this of block class for countries
 * @var App\Blocks\BlockAbstract $publishers $this of block class for publishers
 */
?>

<div class="content-container">
    <div class="entity-container">
            <form method="post" action="">
                <div class="entity-container__input-row">
                    <label for="authorName">
                        ФИО автора:
                    </label>
                    <input
                        id="authorName"
                        name="authorName"
                        placeholder="ФИО автора"
                        required
                    >

                    <input
                        class="entity-container__button entity-container__button_small"
                        type="submit"
                        name="newLib"
                    >
                </div>
            </form>
        </div>
</div>