<?php
/**
 * @var App\Blocks\CreateBookBlock $this $this of block class for creation
 */
?>
<form method="post" action="">
    <input name="bookName" placeholder="Book name" required>

    <input
        type="number"
        name="bookPrice"
        placeholder="price"
        required
    >

    <select name="authorId" required>
        <option disabled>Выберите Автора</option>
        <?php foreach ($this->getAuthors() as $author):?>
        <option
            value="<?= $author['id']?>"
        >
            <?= $author['name']?>
        </option>
        <?php endforeach;?>
    </select>

    <select name="countryId">
        <option disabled>Выберите страну</option>
        <?php foreach ($this->getCountries() as $country):?>
            <option
                    value="<?= $country['id']?>"
            >
                <?= $country['name']?>
            </option>
        <?php endforeach;?>
    </select>

    <select name="publisherId" required>
        <option disabled>Выберите издателя</option>
        <?php foreach ($this->getPublishers() as $publisher):?>
            <option
                    value="<?= $publisher['id']?>"
            >
                <?= $publisher['name']?>
            </option>
        <?php endforeach;?>
    </select>

    <input type="date" name="bookDate" required>

    <input type="submit" name="newBook">
</form>
