<?php
/**
 * @var App\Blocks\FormBlock $this->model of block class for creation
 */
?>
<?php $bookModel = $this->getOneModel('bookModel') ?>
<div class="content-container">
    <form method="post" action="">
        <div class="entity-container entity-container_column">
            <?php $this->renderToken() ?>

            <span class="entity-container__input-row">
                <label for="bookName"> Название книги:</label>
                <input
                    id="bookName"
                    name="bookName"
                    placeholder="Book name"
                    value="<?= $bookModel->getName() ?>"
                    required
                >
            </span>

            <span class="entity-container__input-row">
                <label for="price"> Цена: </label>
                <input
                    id="price"
                    type="number"
                    name="bookPrice"
                    placeholder="price"
                    value="<?= $bookModel->getPrice() ?>"
                    required
                >
            </span>

            <span class="entity-container__input-row">
                <label for="author"> Автор:</label>
                <select name="authorId" required id="author">
                    <option disabled>Выберите Автора</option>
                    <?php foreach ($this->getOneModel('authorsModel')->getData() as $author): ?>
                        <option value="<?= $author->getId() ?>">
                            <?= $author->getName() ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </span>

            <span class="entity-container__input-row">
                <label for="country">Страна: </label>
                <select name="countryId" id="country">
                    <option disabled>Выберите страну</option>
                    <?php foreach ($this->getOneModel('countriesModel')->getData() as $country): ?>
                        <option value="<?= $country['id'] ?>">
                            <?= $country['name'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </span>

            <span class="entity-container__input-row">
                <label for="publisher"> Издатель: </label>
                <select id="publisher" name="publisherId" required>
                    <option disabled>Выберите издателя</option>
                    <?php foreach ($this->getOneModel('publishersModel')->getData() as $publisher): ?>
                        <option value="<?= $publisher->getId() ?>">
                            <?= $publisher->getName() ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </span>

            <span class="entity-container__input-row">
                <label for="category"> Жанр: </label>
                <select id="category" name="categoryId" required>
                    <option disabled>Выберите Жанр</option>
                    <?php foreach ($this->getOneModel('categoriesModel')->getData() as $categories): ?>
                        <option value="<?= $categories['id'] ?>">
                            <?= $categories['name'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </span>

            <span class="entity-container__input-row">
                <label for="date"> Дата написания</label>
                <input
                    id="date"
                    type="date"
                    name="bookDate"
                    required
                >
            </span>

            <input type="submit" name="newBook" class="entity-container__button entity-container__button_small">
        </div>
    </form>
</div>