<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for edit user
 */
?>

<?php
 $data = $this->model['user']->getData();
 $err  = $this->model['session']->getError();
 if (isset($err)) {
    require_once APP_ROOT . '/App/templates/error.phtml';
 }
?>
<div class="content-container">
    <form method="post" action="/editUser">
        <div class="entity-container entity-container_column">

            <input
                    id="token"
                    name="token"
                    type="hidden"
                    value="<?= $this->getToken() ?>"
            >

            <div class="entity-container__input-row">
                <label for="name">
                    Имя
                </label>
                <input
                    id="name"
                    name="name"
                    placeholder="Имя"
                    value="<?= $data['name']?>"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <label for="surname">
                    Фамилия
                </label>
                <input
                    id="surname"
                    name="surname"
                    placeholder="фамилия"
                    value="<?= $data['surname']?>"
                    required
                >
            </div>


            <div class="entity-container__input-row">
                <label for="password">
                    Пароль
                </label>
                <input
                    id="password"
                    name="password"
                    placeholder="Пароль"
                    type="password"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <input
                    class="entity-container__button"
                    type="submit"
                    name="newLib"
                    value="Изменить"
                >

                <a
                    class="entity-container__button"
                    href="/profile"
                >
                    Отмена
                </a>
            </div>
        </div>
    </form>
</div>