<?php
/**
 * @var App\Blocks\Block $this-> $this of block class for user session
 */

$model = $this->getUser();
?>

<div class="content-container">
    <div class="entity-container">
        <div class="entity-container__side-block">

            <div class="entity-container__info-block">
                <h2>
                    <?= $this->secureText($model->getName()) ?>
                    <?= $this->secureText($model->getSurname()) ?>
                </h2>
            </div>

            <div class="entity-container__left-buttons">
                <a
                    class="entity-container__button"
                    href="/logOut"
                >
                    Выйти
                </a>

                <a
                    class="entity-container__button"
                    href="/editUser"
                >
                    Редактировать
                </a>
            </div>

            <a
                class="entity-container__button"
                href="/tookenBooks"
            >
                Взятые книги
            </a>
        </div>
    </div>
</div>
