<?php
/**
 * @var App\Blocks\Block $this->model of block class for publishers
 */
?>

<div class="content-container content-container_list">

    <div class="entity-container entity-container_list">
        <?php foreach ($this->model->getData() as $publisher): ?>
            <a href="../publisher?id=<?= $publisher['id']?>" class="entity-container__button">
                <h2><?= $publisher['name']?></h2>
            </a>
        <?php endforeach; ?>
    </div>

    <div class="recommend-list">
        <a href="" class="recommend-list__element">
            Худ. литература
        </a>

        <a href="" class="recommend-list__element">
            Научная литература
        </a>

        <a href="" class="recommend-list__element">
            Отечественная
        </a>

        <a href="" class="recommend-list__element">
            Зарубежная
        </a>

        <a href="" class="recommend-list__element">
            Достоевский
        </a>

        <a href="" class="recommend-list__element">
            Пушкин
        </a>

        <a href="" class="recommend-list__element">
            Философия
        </a>

        <a href="" class="recommend-list__element">
            Другое
        </a>
    </div>
</div>

