<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for registration
 */
 $err  = $this->model->getError();
 if (isset($err)) {
     require_once APP_ROOT . '/App/templates/error.phtml';
 }
?>
<div class="content-container">
    <form method="post" action="/postRegistration">
        <div class="entity-container entity-container_column">

            <input
                    id="token"
                    name="token"
                    type="hidden"
                    value="<?= $this->getToken() ?>"
            >

            <div class="entity-container__input-row">
                <label for="login">
                    Логин
                </label>
                <input
                    id="login"
                    name="login"
                    placeholder="Логин"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <label for="name">
                    Имя
                </label>
                <input
                    id="name"
                    name="name"
                    placeholder="Имя"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <label for="surname">
                    Фамилия
                </label>
                <input
                    id="surname"
                    name="surname"
                    placeholder="фамилия"
                    required
                >
            </div>


            <div class="entity-container__input-row">
                <label for="password">
                    Пароль
                </label>
                <input
                    id="password"
                    name="password"
                    placeholder="Пароль"
                    type="password"
                    required
                >
            </div>

            <div class="entity-container__input-row">
                <input
                    class="entity-container__button"
                    type="submit"
                    name="newLib"
                    value="Зарегистрироваться"
                >

                <a
                    class="entity-container__button"
                    href="/login"
                >
                    Уже зарегистрированы?
                </a>
            </div>
        </div>
    </form>
</div>