<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for books
 */
?>

<div class="content-container content-container_list">
    <div class="entity-container entity-container_list">
        <?php foreach ($this->model->getData() as $book): ?>
            <a href="/book?id=<?= $book['id'] ?>" class="entity-container__button">
                <h2><?= $book['name']?></h2>
                <h3><?= $book['author']?></h3>
            </a>
        <?php endforeach; ?>
    </div>
</div>
