<?php
/**
 * @var App\Blocks\Block $this->model $this of block class for books
 */
?>

<div class="content-container content-container_list">
    <div class="entity-container entity-container_list">
        <?php foreach ($this->getModel()->getData() as $book): ?>
            <a href="/book?id=<?= $this->toNormalText($book->getId()) ?>" class="entity-container__button">
                <h2><?= $this->toNormalText($book->getName()) ?></h2>
            </a>
        <?php endforeach; ?>
    </div>
</div>
