<?php
/**
 * @var App\Blocks\CategoriesBlock $this
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categories</title>


    <?php require_once 'App/templates/stylesTemplate.php'?>
</head>
<body>
<?php include 'App/templates/headerTemplate.phtml'?>
<ul>
<?php foreach ($this->getData() as $item):?>
    <li><?= $item ?></li>
    <?php endforeach; ?>
</ul>
<?php include 'App/templates/footerTemplate.phtml'?>
</body>
</html>