<header class="header">

    <nav class="navigation">
        <ul class="navigation__list">
            <li class="navigation__marker">
                <a href="../" class="navigation__link">
                    Главная
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../books" class="navigation__link">
                    Книги
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../libraries" class="navigation__link">
                    Библиотеки
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../authors" class="navigation__link">
                    Писатели
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../publishers" class="navigation__link">
                    Издатели
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../createBook" class="navigation__link">
                    Добавить книгу
                </a>
            </li>
        </ul>
    </nav>

</header>