
<header class="header">

    <nav class="navigation">
        <ul class="navigation__list">
            <li class="navigation__marker">
                <a href=".." class="navigation__link">
                    Главная
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../books" class="navigation__link">
                    Книги
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../libraries" class="navigation__link">
                    Библиотеки
                </a>
            </li>

            <li class="navigation__marker">
                <a href="../authors" class="navigation__link">
                    Писатели
                </a>
            </li>

        </ul>


        <ul class="navigation__list">
            <?php if (!$this->isLoggedIn()) {
                $this->renderLoginButton();
            } ?>

            <li class="navigation__marker">
                <a href="/profile" class="navigation__link">
                    Профиль
                </a>
            </li>
        </ul>
    </nav>

</header>