<?php

use App\Blocks\BlocksInterface;

function renderPage($templateName, BlocksInterface $block)
{
    echo '<!DOCTYPE html>
        <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <title>Book society</title>';

    include 'App/templates/stylesTemplate.php';
    echo '</head>';
    echo '<body>';

    include 'App/templates/headerTemplate.phtml';

    include "App/View/$templateName.phtml";

    include 'App/templates/footerTemplate.phtml';

    echo '</body>';
    echo '</html>';
}
